In [1]:
import numpy as np

In [5]:
new=np.array([[0,1],[2,3]])
print(new)

[[0 1]
 [2 3]]


In [7]:
random_array=np.random.rand(3,4)
print(random_array)

[[0.90848022 0.53330355 0.80695796 0.13357839]
 [0.67702634 0.87119761 0.49463199 0.32276985]
 [0.83132186 0.63543446 0.38805045 0.09200435]]


In [10]:
new2=np.ones([2,2])
new3=np.zeros([2,2])
print(new2)
print(new3)

[[1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]]


In [15]:
q4=np.random.rand(6,3)
new4=np.transpose(q4)
print(q4)
print(new4)

[[0.66999475 0.86163669 0.38117046]
 [0.89310161 0.59539984 0.25086805]
 [0.54321945 0.24092055 0.97064294]
 [0.96185418 0.28358483 0.23550511]
 [0.70354478 0.18241881 0.07442344]
 [0.95183709 0.85619608 0.92938972]]
[[0.66999475 0.89310161 0.54321945 0.96185418 0.70354478 0.95183709]
 [0.86163669 0.59539984 0.24092055 0.28358483 0.18241881 0.85619608]
 [0.38117046 0.25086805 0.97064294 0.23550511 0.07442344 0.92938972]]


In [22]:
n=2
p=3
m=4
random1=np.random.rand(n,p)
random2=np.random.rand(p,m)
print(random1,"\n",random2)

dot_product=np.dot(random1,random2)
print(dot_product)

[[0.14059024 0.90436874 0.49221081]
 [0.10534794 0.62923361 0.55888076]] 
 [[0.00455599 0.36774719 0.78508185 0.00107841]
 [0.49110096 0.06594828 0.59071911 0.22291116]
 [0.84483985 0.49829508 0.08612774 0.39301517]]
[[0.86061619 0.35660945 0.68699575 0.39519181]
 [0.78166193 0.35872582 0.50254221 0.36002542]]


In [23]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [26]:
%cd /content/drive/MyDrive/Colab Notebooks
!ls

/content/drive/MyDrive/Colab Notebooks
Pandas.ipynb	     Setup1.ipynb  Tutorial03.ipynb
Python_Script.ipynb  Setup.ipynb   Untitled0.ipynb


In [27]:
!git config --global user.email "25005876@siswa.um.edu.my"
!git config --global user.name "josephineding-2025"

In [32]:
%cd ../git_repos/data-science-toolkit/

/content/drive/MyDrive/git_repos/data-science-toolkit


In [33]:
!git add Tutorial03.ipynb
!git commit -m "Add Notebook from Colab to GitHub"
!git push

fatal: pathspec 'Tutorial03.ipynb' did not match any files
On branch library/numpy
nothing to commit, working tree clean
fatal: The current branch library/numpy has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin library/numpy



In [34]:
!git status

On branch library/numpy
nothing to commit, working tree clean


In [35]:
!git switch main

Switched to branch 'main'
Your branch is ahead of 'origin/main' by 1 commit.
  (use "git push" to publish your local commits)


In [36]:
!git add Tutorial03.ipynb
!git commit -m "Add Notebook from Colab to GitHub"
!git push

fatal: pathspec 'Tutorial03.ipynb' did not match any files
On branch main
Your branch is ahead of 'origin/main' by 1 commit.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean
fatal: could not read Username for 'https://github.com': No such device or address


In [47]:
%cd /content/drive/MyDrive/Colab Notebooks

[Errno 20] Not a directory: 'Tutorial03.ipynb'
/content/drive/MyDrive/Colab Notebooks


In [ ]:
!cp Tutorial03.ipynb /