In [7]:
import numpy as np

In [8]:
new=np.array([[0,1],[2,3]])
print(new)

[[0 1]
 [2 3]]


In [9]:
random_array=np.random.rand(3,4)
print(random_array)

[[0.52345618 0.76560656 0.48528739 0.44906709]
 [0.55868334 0.25310122 0.00296731 0.41386079]
 [0.20223647 0.56949838 0.01438308 0.7211389 ]]


In [10]:
new2=np.ones([2,2])
new3=np.zeros([2,2])
print(new2)
print(new3)

[[1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]]


In [11]:
q4=np.random.rand(6,3)
new4=np.transpose(q4)
print(q4)
print(new4)

[[0.86305183 0.46631213 0.49440714]
 [0.61605995 0.77440413 0.31080211]
 [0.2460325  0.69577227 0.95444808]
 [0.49298205 0.39351199 0.95763497]
 [0.5726214  0.32783699 0.86699383]
 [0.33849335 0.69297166 0.90448154]]
[[0.86305183 0.61605995 0.2460325  0.49298205 0.5726214  0.33849335]
 [0.46631213 0.77440413 0.69577227 0.39351199 0.32783699 0.69297166]
 [0.49440714 0.31080211 0.95444808 0.95763497 0.86699383 0.90448154]]


In [13]:
n=2
p=3
m=4
random1=np.random.rand(n,p)
random2=np.random.rand(p,m)
print(random1,"\n",random2)

dot_product=np.dot(random1,random2)
print(dot_product)

[[0.0838413  0.24521474 0.64565579]
 [0.41873713 0.40758773 0.22675012]] 
 [[0.50781059 0.91552943 0.61867283 0.19428072]
 [0.1968556  0.54096479 0.59608551 0.48851909]
 [0.30258578 0.50981821 0.03217855 0.28578202]]
[[0.28621366 0.5385788  0.21881556 0.32059765]
 [0.36148643 0.71945812 0.50931491 0.34526804]]


In [14]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [15]:
%cd /content/drive/MyDrive/git_repos

/content/drive/MyDrive/git_repos


In [17]:
%cd data-science-toolkit

/content/drive/MyDrive/git_repos/data-science-toolkit


In [18]:
!ls

'python_basics (1).ipynb'   python_basics.ipynb   README.md


In [20]:
!cp "/content/drive/MyDrive/Colab Notebooks/Tutorial03.ipynb" "/content/drive/MyDrive/git_repos/data-science-toolkit/"


In [22]:
!git status

On branch main
Your branch is ahead of 'origin/main' by 3 commits.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean


In [26]:
!git add Tutorial03.ipynb
!git commit -m "Add Notebook from Colab to GitHub"
!git push https://josephineding-2025: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@github.com/josephineding-2025/data-science-toolkit.git main

On branch main
Your branch is ahead of 'origin/main' by 3 commits.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean
To https://github.com/josephineding-2025/data-science-toolkit.git
 ! [rejected]        main -> main (fetch first)
error: failed to push some refs to 'https://github.com/josephineding-2025/data-science-toolkit.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
